# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recognizers.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recognizers.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11recognizers.proto\"0\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x13\n\x0b\x63ultureCode\x18\x02 \x01(\t\"!\n\x0fRecognizeResult\x12\x0e\n\x06result\x18\x01 \x01(\t2I\n\x0fRecognizersText\x12\x36\n\x12GetRecognizeResult\x12\x0c.TextRequest\x1a\x10.RecognizeResult\"\x00\x62\x06proto3')
)




_TEXTREQUEST = _descriptor.Descriptor(
  name='TextRequest',
  full_name='TextRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='TextRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cultureCode', full_name='TextRequest.cultureCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=69,
)


_RECOGNIZERESULT = _descriptor.Descriptor(
  name='RecognizeResult',
  full_name='RecognizeResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='RecognizeResult.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['TextRequest'] = _TEXTREQUEST
DESCRIPTOR.message_types_by_name['RecognizeResult'] = _RECOGNIZERESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextRequest = _reflection.GeneratedProtocolMessageType('TextRequest', (_message.Message,), {
  'DESCRIPTOR' : _TEXTREQUEST,
  '__module__' : 'recognizers_pb2'
  # @@protoc_insertion_point(class_scope:TextRequest)
  })
_sym_db.RegisterMessage(TextRequest)

RecognizeResult = _reflection.GeneratedProtocolMessageType('RecognizeResult', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNIZERESULT,
  '__module__' : 'recognizers_pb2'
  # @@protoc_insertion_point(class_scope:RecognizeResult)
  })
_sym_db.RegisterMessage(RecognizeResult)



_RECOGNIZERSTEXT = _descriptor.ServiceDescriptor(
  name='RecognizersText',
  full_name='RecognizersText',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=106,
  serialized_end=179,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRecognizeResult',
    full_name='RecognizersText.GetRecognizeResult',
    index=0,
    containing_service=None,
    input_type=_TEXTREQUEST,
    output_type=_RECOGNIZERESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECOGNIZERSTEXT)

DESCRIPTOR.services_by_name['RecognizersText'] = _RECOGNIZERSTEXT

# @@protoc_insertion_point(module_scope)
